# Docker Compose para testing local - Un solo contenedor
# Para usar: docker-compose -f docker-compose.single.yml up --build

version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.single
    container_name: cv_app_local
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Bind mount para desarrollo local
    environment:
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin  
      - ADMIN_PASSWORD_HASH=b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - JWT_SECRET=local_development_secret
    restart: unless-stopped

# Para usar:
# docker-compose -f docker-compose.single.yml up --build
# 
# Acceso:
# - App: http://localhost:8000
# - Admin: http://localhost:8000/admin (admin/password123)
# - Health: http://localhost:8000/health
# - API: http://localhost:8000/api/content/