# Stack CV App - Configuración Directa con IP
# Cambia "TU_IP_SERVIDOR" por la IP real de tu servidor
# Frontend: Puerto 8006 | Backend: Puerto 8007

version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: cv_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
      MONGO_INITDB_DATABASE: cv_database
    volumes:
      - mongodb_data:/data/db
    networks:
      - cv_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.portainer
    container_name: cv_backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://admin:securepassword123@mongodb:27017/cv_database?authSource=admin
      DB_NAME: cv_database
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD_HASH: b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      JWT_SECRET: production_jwt_secret_change_this
      CORS_ORIGINS: "*"
    ports:
      - "8007:8001"
    networks:
      - cv_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.portainer
      args:
        # 👇 CAMBIAR "TU_IP_SERVIDOR" POR TU IP REAL
        REACT_APP_BACKEND_URL: http://TU_IP_SERVIDOR:8007
    container_name: cv_frontend
    restart: unless-stopped
    environment:
      # 👇 CAMBIAR "TU_IP_SERVIDOR" POR TU IP REAL  
      REACT_APP_BACKEND_URL: http://TU_IP_SERVIDOR:8007
    ports:
      - "8006:3000"
    networks:
      - cv_network
    depends_on:
      - backend

  data-init:
    build:
      context: ./backend
      dockerfile: Dockerfile.portainer
    container_name: cv_data_init
    environment:
      MONGO_URL: mongodb://admin:securepassword123@mongodb:27017/cv_database?authSource=admin
      DB_NAME: cv_database
    networks:
      - cv_network
    depends_on:
      - mongodb
      - backend
    command: >
      sh -c "
        echo '⏳ Esperando servicios (30s)...' &&
        sleep 30 &&
        echo '🔌 Conectando a MongoDB...' &&
        python -c 'from motor.motor_asyncio import AsyncIOMotorClient; import asyncio; import os; asyncio.run(AsyncIOMotorClient(os.environ[\"MONGO_URL\"]).admin.command(\"ping\"))' &&
        echo '📝 Inicializando datos del CV...' &&
        python init_data.py &&
        echo '✅ ¡CV App lista! Frontend: http://TU_IP_SERVIDOR:8006'
      "
    restart: "no"

networks:
  cv_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

# 📋 INSTRUCCIONES DE USO:
# 1. Reemplaza "TU_IP_SERVIDOR" por tu IP real (ej: 192.168.1.100)
# 2. Sube este YML a Portainer como nuevo stack
# 3. Deploy y espera 1-2 minutos
# 4. Accede: http://TU_IP_SERVIDOR:8006
# 5. Admin: http://TU_IP_SERVIDOR:8006/admin (admin/password123)