version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: cv_app_fixed
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - JWT_SECRET=production_jwt_secret_change_this
    volumes:
      - cv_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  cv_data:
    driver: local