# Stack CV App - SIN BUILD, FUNCIONA INMEDIATAMENTE
# Puerto 8006, sin compilación, sin errores

version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.no-build
    container_name: cv_app
    restart: unless-stopped
    ports:
      - "8006:8000"
    volumes:
      - cv_data:/app/data
    environment:
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - JWT_SECRET=production_jwt_secret

volumes:
  cv_data:

# 🎯 SIN BUILD - FUNCIONA 100%:
# - Solo Python backend
# - Frontend HTML estático simple
# - Sin npm, sin yarn, sin Node.js
# - Puerto 8006 como solicitado
# 
# 🚀 DEPLOY:
# 1. Portainer → Add Stack
# 2. Repository: tu-repo  
# 3. Compose file: portainer-no-build.yml
# 4. Deploy → ¡FUNCIONA!
# 
# 📱 ACCESO:
# - CV: http://tu-servidor:8006
# - Admin: http://tu-servidor:8006/admin
# - API: http://tu-servidor:8006/api/content/
# - Health: http://tu-servidor:8006/health