# Stack CV App - Para usar con WEB EDITOR en Portainer
# Copia todo este contenido en el editor web de Portainer
# IMPORTANTE: Asegurar que frontend esté compilado antes

version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.prebuilt
    container_name: cv_app_all_in_one
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - cv_data:/app/data
    environment:
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - JWT_SECRET=production_jwt_secret_change_this
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  cv_data:
    driver: local

# INSTRUCCIONES PARA USO CON WEB EDITOR:
#
# 1. PREPARAR (ejecutar en servidor):
#    cd /path/to/your/app
#    ./prepare_for_deploy.sh
#
# 2. EN PORTAINER:
#    - Stacks → Add Stack
#    - Name: cv-app-single
#    - Build method: Web editor
#    - Copiar este contenido completo
#    - Deploy stack
#
# 3. ACCESO DESPUÉS DEL DEPLOY:
#    - App: http://tu-servidor:8000
#    - Admin: http://tu-servidor:8000/admin
#    - Health: http://tu-servidor:8000/health
#
# 4. LOGIN ADMIN:
#    - Usuario: admin
#    - Password: password123