# Stack Minimal para Portainer - Sin Health Checks
# Usar esta versión si la anterior aún da problemas

services:
  # MongoDB Database - SIN health check
  mongodb:
    image: mongo:5.0
    container_name: cv_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-securepassword123}
      MONGO_INITDB_DATABASE: ${DB_NAME:-cv_database}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cv_internal
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Backend API - SIN health check
  backend:
    image: cv_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv_backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-securepassword123}@mongodb:27017/${DB_NAME:-cv_database}?authSource=admin
      DB_NAME: ${DB_NAME:-cv_database}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH:-b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890}
      JWT_SECRET: ${JWT_SECRET:-production_jwt_secret_very_long_key_change_this_in_production}
      PYTHONPATH: /app
    expose:
      - "8001"
    networks:
      - cv_internal
      - npm_proxy
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend - SIN health check
  frontend:
    image: cv_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: ${BACKEND_URL:-https://api.yourdomain.com}
    container_name: cv_frontend
    restart: unless-stopped
    environment:
      REACT_APP_BACKEND_URL: ${BACKEND_URL:-https://api.yourdomain.com}
    expose:
      - "3000"
    networks:
      - cv_internal
      - npm_proxy
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Data Initializer
  data-init:
    image: cv_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv_data_init
    environment:
      MONGO_URL: mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-securepassword123}@mongodb:27017/${DB_NAME:-cv_database}?authSource=admin
      DB_NAME: ${DB_NAME:-cv_database}
    networks:
      - cv_internal
    depends_on:
      - mongodb
    command: >
      sh -c "
        echo 'Esperando MongoDB...' &&
        sleep 60 &&
        echo 'Inicializando datos...' &&
        python init_data.py &&
        echo 'Datos inicializados correctamente'
      "
    restart: "no"

networks:
  cv_internal:
    driver: bridge
    internal: true
  npm_proxy:
    external: true

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local