version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: cv_app_fixed
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=38e9c8ff64f9bff540a8d715970fa0fd:c3350383271174906b081329734760df3cff51f38564664c2e6782ef95cbd688
      - JWT_SECRET=production_jwt_secret_change_this
    volumes:
      - cv_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  cv_data:
    driver: local