# Stack CV App - MINIMAL QUE FUNCIONA
version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: cv_app
    restart: unless-stopped
    ports:
      - "8006:8000"
    volumes:
      - cv_data:/app/data
    environment:
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - JWT_SECRET=production_jwt_secret

volumes:
  cv_data: