version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: cv_app_production
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=9eadfdc77f85614879a4957ccac7e679:8784f9085381abd4202181d927565dd152d0a4ada3b5ac117f89c3720460a70b
      - JWT_SECRET=production_jwt_secret_change_this
    volumes:
      - cv_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  cv_data:
    driver: local