# Stack CV App - Con CORS y Variables de Entorno Corregidas
# Frontend: Puerto 8006 | Backend: Puerto 8007
# IP del servidor: 192.168.1.18

version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: cv_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
      MONGO_INITDB_DATABASE: cv_database
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cv_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.no-healthcheck
    container_name: cv_backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://admin:securepassword123@mongodb:27017/cv_database?authSource=admin
      DB_NAME: cv_database
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD_HASH: b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      JWT_SECRET: production_jwt_secret_change_this
      # CORS más permisivo para debug
      CORS_ORIGINS: "*"
    ports:
      - "8007:8001"
    networks:
      - cv_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.env-fixed
      args:
        # IP real del servidor
        REACT_APP_BACKEND_URL: http://192.168.1.18:8007
    container_name: cv_frontend
    restart: unless-stopped
    environment:
      # IP real del servidor
      REACT_APP_BACKEND_URL: http://192.168.1.18:8007
    ports:
      - "8006:3000"
    networks:
      - cv_network
    depends_on:
      - backend

networks:
  cv_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

# 📋 INSTRUCCIONES DETALLADAS:
# 1. Deploy este stack en Portainer
# 2. Espera 5 minutos a que todo compile y esté corriendo
# 3. Ve a: http://192.168.1.18:8006/admin
# 4. Login: admin / password123
# 5. Ve a pestaña "CORS" y ejecuta tests
# 6. Si CORS funciona, ve a pestaña "Import" → "Inicialización Rápida"