# Stack CV App - ULTRA SIMPLE QUE FUNCIONA
# Puerto 8006 como solicitado

version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: cv_app
    restart: unless-stopped
    ports:
      - "8006:8000"  # Puerto 8006 externo como solicitado
    volumes:
      - cv_data:/app/data
    environment:
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - JWT_SECRET=production_jwt_secret

volumes:
  cv_data:

# 🎯 ULTRA SIMPLE:
# - Solo usa NPM (sin yarn)
# - Sin health checks complicados
# - Puerto 8006 como antes
# - Dockerfile minimalista
# 
# 🚀 DEPLOY:
# 1. Portainer → Add Stack
# 2. Repository: tu-repo
# 3. Compose file: portainer-ultra-simple.yml
# 4. Deploy
# 
# 📱 ACCESO:
# - App: http://tu-servidor:8006
# - Admin: http://tu-servidor:8006/admin
# - Login: admin / password123