# Stack CV App - JSON Storage Simple
# SOLO 2 contenedores: Frontend + Backend
# Sin MongoDB - Datos en archivos JSON

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.no-healthcheck
    container_name: cv_backend
    restart: unless-stopped
    environment:
      CORS_ORIGINS: "*"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD_HASH: b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      JWT_SECRET: production_jwt_secret_change_this
    ports:
      - "8007:8001"
    volumes:
      - cv_data:/app/data  # Volumen para persistir datos JSON
    networks:
      - cv_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.portainer
      args:
        REACT_APP_BACKEND_URL: http://192.168.1.18:8007
    container_name: cv_frontend
    restart: unless-stopped
    environment:
      REACT_APP_BACKEND_URL: http://192.168.1.18:8007
    ports:
      - "8006:3000"
    networks:
      - cv_network
    depends_on:
      - backend

networks:
  cv_network:
    driver: bridge

volumes:
  cv_data:
    driver: local

# 🎉 CONFIGURACIÓN ULTRA SIMPLIFICADA:
# 
# ✅ VENTAJAS:
# - Solo 2 contenedores (sin MongoDB)
# - Datos persistentes en JSON
# - Backup automático
# - Deploy mucho más rápido
# - Sin problemas de conectividad MongoDB
# - Menos recursos (memoria/CPU)
# 
# 📋 ACCESO:
# Frontend: http://192.168.1.18:8006
# Backend: http://192.168.1.18:8007
# Admin Panel: http://192.168.1.18:8006/admin
# 
# 🔐 LOGIN ADMIN:
# Usuario: admin
# Password: password123
# 
# 📁 DATOS:
# Los datos del CV se guardan en: /app/data/cv_content.json
# Backups automáticos en: /app/data/backups/
# 
# 🚀 CARACTERÍSTICAS:
# - Import/Export JSON
# - Backup automático al guardar
# - Restauración desde backups
# - API REST completa
# - Sistema CMS funcional