# Stack CV App - Un Solo Contenedor (Sin CORS)  
# Frontend + Backend: Puerto 8006
# MongoDB: Interno

version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: cv_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
      MONGO_INITDB_DATABASE: cv_database
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cv_network

  # Aplicación combinada (Frontend + Backend)
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.combined
    container_name: cv_app
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://admin:securepassword123@mongodb:27017/cv_database?authSource=admin
      DB_NAME: cv_database
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD_HASH: b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      JWT_SECRET: production_jwt_secret_change_this
      CORS_ORIGINS: "*"
    ports:
      - "8006:8001"
    networks:
      - cv_network
    depends_on:
      - mongodb

networks:
  cv_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

# 📋 INSTRUCCIONES:
# 1. Deploy este stack en Portainer
# 2. Espera 5 minutos (build del frontend + backend)
# 3. Ve a: http://192.168.1.18:8006 (Frontend)
# 4. Admin Panel: http://192.168.1.18:8006/admin
# 5. API: http://192.168.1.18:8006/api/
# 6. Sin problemas de CORS - todo en el mismo puerto!