# Stack CV App - FINAL WORKING VERSION
# Un solo contenedor, build robusto, funciona siempre

version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile.robust
    container_name: cv_app_final
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - cv_data:/app/data
    environment:
      - CORS_ORIGINS=*
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD_HASH=b8d6c1a9b2e5d7f3:a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890
      - JWT_SECRET=production_jwt_secret_change_this

volumes:
  cv_data:
    driver: local

# 🎯 ULTRA ROBUSTO:
# - Maneja yarn.lock automáticamente (existe o no)
# - Compila frontend durante build
# - No requiere preparación previa
# - Funciona directo desde Git
# 
# 🚀 USO:
# 1. Portainer → Add Stack
# 2. Repository: tu-repo
# 3. Compose file: portainer-final-working.yml
# 4. Deploy → ¡Funciona!
# 
# 📱 ACCESO:
# - App: http://tu-servidor:8000
# - Admin: http://tu-servidor:8000/admin (admin/password123)